export const APP_GUIDE = `
# OwnVoice AI — App Guide

## Overview
OwnVoice AI is a content strategy platform for solo creators and wellness entrepreneurs.
The core loop: build your profile → generate a monthly editorial plan → discover trends & ideas → create content in the Lab → track projects.

## Getting Started (recommended order)
1. Complete your Profile (niche, pillars, persona) at /profile
2. Go to Editorial to generate your first monthly content plan
3. Use Discover to find trending topics aligned with your niche
4. Open the Lab to validate ideas and generate content assets
5. Track each piece of content in Projects

## Pages

### Dashboard (/dashboard)
- Shows your current editorial calendar at a glance
- "Configure & Generate" button opens the full editorial settings on the Editorial page
- Right sidebar: Discover card (trends & ideas), Hot Topics widget, Lab shortcut
- If no plan yet: click "Configure & Generate" to get started

### Editorial Calendar (/editorial)
- Your 4-week content calendar, generated by AI based on your strategy
- Settings panel: Posting Cadence (3×/week up to daily), Content Mix presets (Growth / Balanced / Launch / Authority)
- Content Mix: Value (educational/entertaining), Authority (expertise/trust), Sales (offers/CTAs)
- Routine view: set which content pillar and vibe you post on each day of the week; changing cadence updates the days automatically
- Monthly view: drag-and-drop any post chip to a different date to reschedule it
- Click a post chip to open post details (topic, hook, format, linked project)
- "Extend plan to cover this month" generates posts for months with no content scheduled
- Generate button creates or regenerates your 4-week plan based on current settings

### Discover (/discover)
- Macro Trends: broad cultural and industry signals to stay ahead of the curve
- Niche Trends: signals specific to your content category and audience
- Idea Generator: AI-generated content ideas grounded in real trends, aligned to your pillars

### OwnVoice Lab (/lab)
- Your AI content studio for going from idea to production-ready content
- Validate an idea: get strategic analysis (relevance, angles, risks) before investing time
- Generate assets: hooks, captions, scripts, carousel outlines — all in your brand voice
- Create a Workflow: step-by-step AI-assisted content production from brief to final asset
- Ideas from Discover can be sent directly to the Lab for validation or production

### Projects (/projects)
- Track each content piece from idea → draft → review → published
- Link a project to a specific post slot in your Editorial Calendar
- Create a project from a Lab-validated idea to move it into production

### Profile / Settings (/profile)
- Content pillars: the 3–5 recurring themes your brand stands for (e.g. Mindset, Nutrition, Business)
- Niche & persona: who you are, who you serve, and what makes your voice unique
- These fields drive ALL AI generation across the app (editorial plan, ideas, Lab assets)
- Update pillars or niche here if your strategy evolves

### Integrations (/integrations)
- Connect your Instagram account to enable social publishing features
- TikTok connection coming soon

## Common Questions

Q: Where do I start?
A: Go to Profile first — set your content pillars and niche. Then go to Editorial and hit "Generate My Month" to create your first content plan. After that, Discover and the Lab will give you personalised ideas.

Q: My calendar is empty for this month.
A: Navigate to the Editorial page. If you're viewing a month with no content, you'll see an "Extend plan to cover this month" button. Click it (or use "Configure & Generate") to generate posts for that month.

Q: How do I move a post to a different day?
A: On the Editorial page (not the dashboard), drag any coloured post chip and drop it on the target date. The change saves automatically.

Q: What is the content mix?
A: Value posts educate or entertain your audience. Authority posts demonstrate your expertise and build trust. Sales posts promote your offers or CTAs. The mix percentages control how many of each type appear in your generated plan.

Q: How do I change my posting frequency?
A: Go to the Editorial page → click "Settings" → choose a Cadence (3×, 4×, 5×/week, or Daily). If you're in Routine view, the posting days update automatically when you change cadence.

Q: What is the Routine view?
A: On the Editorial page, switch from Monthly to Routine view to set which content pillar and energy/vibe you post on each scheduled day. This shapes the AI's topic selection when you generate or regenerate your plan.

Q: How do I validate a content idea before creating it?
A: Go to the Lab, enter your idea, and use the Validate feature. You'll get a strategic analysis: relevance to your niche, content angles, and potential risks. Then you can turn it into a full Workflow.

Q: What are content pillars?
A: Pillars are the 3–5 recurring themes that define your brand's expertise (e.g. Gut Health, Stress Management, Meal Prep). Set them in Profile. Every piece of AI-generated content is anchored to a pillar.
`.trim();
